# Generated by Django 4.2.4 on 2023-08-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_jeson', models.CharField(max_length=50000)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(default='', max_length=150)),
                ('address1', models.CharField(default='', max_length=150)),
                ('address2', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=80)),
                ('zip', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
