# Generated by Django 4.2.4 on 2023-08-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='timestamp',
        ),
    ]
